@startuml reversi diagram
class Board {
-board_size
-board
-next_player
+return_board()
+make_move(x,y)
+list_affected(x,y,player)
+moves_exist()
}
class BoardView {
+draw_board()
+prompt_move()
+invalid_move_comment()
+end_screen()
}


class GameLogic {
+initialise(size)
+begin_game()
}
GameLogic  *--  Board
GameLogic  --  Board
GameLogic  --  BoardView
BoardView  --  Board
@enduml